import { FormaPagoInterface, MetodoPagoInterface, RegimenInterface, UsoCfdiInterface,MetodoMonedaPago,ListaBanco } from "../interfaces/shared.interface";

export const LISTADORFCSGENERICOS: string[] = ['XAXX010101000', 'XEXX010101000'];

export const LISTADOREGIMEN: RegimenInterface[] = [{"RegimenFiscal": 601, "descripcion": "General de Ley Personas Morales", "fisica": 0, "moral": 1 }, {"RegimenFiscal": 603, "descripcion": "Personas Morales con Fines no Lucrativos", "fisica": 0, "moral": 1 }, {"RegimenFiscal": 605, "descripcion": "Sueldos y Salarios e Ingresos Asimilados a Salarios", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 606, "descripcion": "Arrendamiento", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 607, "descripcion": "Régimen de Enajenación o Adquisición de Bienes", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 608, "descripcion": "Demás ingresos", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 610, "descripcion": "Residentes en el Extranjero sin Establecimiento Permanente en México", "fisica": 1, "moral": 1 }, {"RegimenFiscal": 611, "descripcion": "Ingresos por Dividendos (socios y accionistas)", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 612, "descripcion": "Personas Físicas con Actividades Empresariales y Profesionales", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 614, "descripcion": "Ingresos por intereses", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 615, "descripcion": "Régimen de los ingresos por obtención de premios", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 616, "descripcion": "Sin obligaciones fiscales", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 620, "descripcion": "Sociedades Cooperativas de Producción que optan por diferir sus ingresos", "fisica": 0, "moral": 1 }, {"RegimenFiscal": 621, "descripcion": "Incorporación Fiscal", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 622, "descripcion": "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras", "fisica": 0, "moral": 1 }, {"RegimenFiscal": 623, "descripcion": "Opcional para Grupos de Sociedades", "fisica": 0, "moral": 1 }, {"RegimenFiscal": 624, "descripcion": "Coordinados", "fisica": 0, "moral": 1 }, {"RegimenFiscal": 625, "descripcion": "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas", "fisica": 1, "moral": 0 }, {"RegimenFiscal": 626, "descripcion": "Régimen Simplificado de Confianza", "fisica": 1, "moral": 1}];

export const LISTADOFORMAPAGO: FormaPagoInterface[] = [{"clave":"01","descripcion":"Efectivo","metodoPago":"PUE"},{"clave":"02","descripcion":"Cheque nominativo","metodoPago":"PUE"},{"clave":"03","descripcion":"Transferencia electrónica de fondos","metodoPago":"PUE"},{"clave":"04","descripcion":"Tarjeta de crédito","metodoPago":"PUE"},{"clave":"05","descripcion":"Monedero electrónico","metodoPago":"PUE"},{"clave":"06","descripcion":"Dinero electrónico","metodoPago":"PUE"},{"clave":"08","descripcion":"Vales de despensa","metodoPago":"PUE"},{"clave":"12","descripcion":"Dación en pago","metodoPago":"PUE"},{"clave":"13","descripcion":"Pago por subrogación","metodoPago":"PUE"},{"clave":"14","descripcion":"Pago por consignación","metodoPago":"PUE"},{"clave":"15","descripcion":"Condonación","metodoPago":"PUE"},{"clave":"17","descripcion":"Compensación","metodoPago":"PUE"},{"clave":"23","descripcion":"Novación","metodoPago":"PUE"},{"clave":"24","descripcion":"Confusión","metodoPago":"PUE"},{"clave":"25","descripcion":"Remisión de deuda","metodoPago":"PUE"},{"clave":"26","descripcion":"Prescripción o caducidad","metodoPago":"PUE"},{"clave":"27","descripcion":"A satisfacción del acreedor","metodoPago":"PUE"},{"clave":"28","descripcion":"Tarjeta de débito","metodoPago":"PUE"},{"clave":"29","descripcion":"Tarjeta de servicios","metodoPago":"PUE"},{"clave":"99","descripcion":"Por definir","metodoPago":"PPD"},{"clave":"30","descripcion":"Aplicacion de Anticipo","metodoPago":"PUE"},{"clave":"31","descripcion":"Intermediario pagos","metodoPago":"PUE"}];

export const LISTADOUSOCFDI: UsoCfdiInterface[] = [{"nombre": "Adquisición de mercancías.", "uso": "G01", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Devoluciones, descuentos o bonificaciones.", "uso": "G02", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Gastos en general.", "uso": "G03", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Construcciones.", "uso": "I01", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Mobiliario y equipo de oficina por inversiones.", "uso": "I02", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Equipo de transporte.", "uso": "I03", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Equipo de computo y accesorios.", "uso": "I04", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Dados, troqueles, moldes, matrices y herramental.", "uso": "I05", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Comunicaciones telefónicas.", "uso": "I06", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Comunicaciones satelitales.", "uso": "I07", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Otra maquinaria y equipo.", "uso": "I08", "regimen": [601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626]}, {"nombre": "Honorarios médicos, dentales y gastos hospitalarios.", "uso": "D01", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Gastos médicos por incapacidad o discapacidad.", "uso": "D02", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Gastos funerales.", "uso": "D03", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Donativos.", "uso": "D04", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).", "uso": "D05", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Aportaciones voluntarias al SAR.", "uso": "D06", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Primas por seguros de gastos médicos.", "uso": "D07", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Gastos de transportación escolar obligatoria.", "uso": "D08", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.", "uso": "D09", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Pagos por servicios educativos (colegiaturas).", "uso": "D10", "regimen": [605, 606, 608, 611, 612, 614, 607, 615, 625]}, {"nombre": "Sin efectos fiscales.", "uso": "S01", "regimen": [601, 603, 605, 606, 608, 610, 611, 612, 614, 616, 620, 621, 622, 623, 624, 607, 615, 625, 626]}, {"nombre": "Pagos", "uso": "CP0", "regimen": [601, 603, 605, 606, 608, 610, 611, 612, 614, 616, 620, 621, 622, 623, 624, 607, 615, 625, 626]}, {"nombre": "Nómina", "uso": "CN0", "regimen": [605]}];


export const LISTADOMETODOPAGO: MetodoPagoInterface[] = [{"metodo": "PUE", "descripcion": "Pago en una sola exhibición"}, {"metodo": "PPD", "descripcion": "Pago en parcialidades o diferido"}]
export const LISTAMONEDADEPAGO: MetodoMonedaPago[]=[{"forma":"AME","descripcion":"Peso Mexicano"},{"forma":"DAM","descripcion":"Dolar Americano"}]
export const LISTABANCO:ListaBanco[]=[{"id_Banco":"1","c_Banco":"002","Descripcion":"BANAMEX","NombreRazonsocial":"Banco Nacional de M"},
    {"id_Banco":"2","c_Banco":"006","Descripcion":"BANCOMEXT","NombreRazonsocial":"Banco Nacional de Comercio Exterior, Sociedad Nacional de Cr"},
    {"id_Banco":"3","c_Banco":"009","Descripcion":"BANOBRAS","NombreRazonsocial":"Banco Nacional de Obras y Servicios P"},
    {"id_Banco":"4","c_Banco":"012","Descripcion":"BBVA BANCOMER","NombreRazonsocial":"BBVA Bancomer, S.A., Instituci"},
    {"id_Banco":"5","c_Banco":"014","Descripcion":"SANTANDER","NombreRazonsocial":"Banco Santander (M"},
    {"id_Banco":"6","c_Banco":"019","Descripcion":"BANJERCITO","NombreRazonsocial":"Banco Nacional del Ej"},
    {"id_Banco":"7","c_Banco":"021","Descripcion":"HSBC","NombreRazonsocial":"HSBC M"},
    {"id_Banco":"8","c_Banco":"030","Descripcion":"BAJIO","NombreRazonsocial":"Banco del Baj"},
    {"id_Banco":"9","c_Banco":"032","Descripcion":"IXE","NombreRazonsocial":"IXE Banco, S.A., Instituci"},
    {"id_Banco":"10","c_Banco":"036","Descripcion":"INBURSA","NombreRazonsocial":"Banco Inbursa, S.A., Instituci"},
    {"id_Banco":"11","c_Banco":"037","Descripcion":"INTERACCIONES","NombreRazonsocial":"Banco Interacciones, S.A., Instituci"},
    {"id_Banco":"12","c_Banco":"042","Descripcion":"MIFEL","NombreRazonsocial":"Banca Mifel, S.A., Instituci"},
    {"id_Banco":"13","c_Banco":"044","Descripcion":"SCOTIABANK","NombreRazonsocial":"Scotiabank Inverlat, S.A."},
    {"id_Banco":"14","c_Banco":"058","Descripcion":"BANREGIO","NombreRazonsocial":"Banco Regional de Monterrey, S.A., Instituci"},
    {"id_Banco":"15","c_Banco":"059","Descripcion":"INVEX","NombreRazonsocial":"Banco Invex, S.A., Instituci"},
    {"id_Banco":"16","c_Banco":"060","Descripcion":"BANSI","NombreRazonsocial":"Bansi, S.A., Instituci"},
    {"id_Banco":"17","c_Banco":"062","Descripcion":"AFIRME","NombreRazonsocial":"Banca Afirme, S.A., Instituci"},
    {"id_Banco":"18","c_Banco":"072","Descripcion":"BANORTE","NombreRazonsocial":"Banco Mercantil del Norte, S.A., Instituci"},
    {"id_Banco":"19","c_Banco":"102","Descripcion":"THE ROYAL BANK","NombreRazonsocial":"The Royal Bank of Scotland M"},
    {"id_Banco":"20","c_Banco":"103","Descripcion":"AMERICAN EXPRESS","NombreRazonsocial":"American Express Bank (M"},
    {"id_Banco":"21","c_Banco":"106","Descripcion":"BAMSA","NombreRazonsocial":"Bank of America M"},
    {"id_Banco":"22","c_Banco":"108","Descripcion":"TOKYO","NombreRazonsocial":"Bank of Tokyo-Mitsubishi UFJ (M"},
    {"id_Banco":"23","c_Banco":"110","Descripcion":"JP MORGAN","NombreRazonsocial":"Banco J.P. Morgan, S.A., Instituci"},
    {"id_Banco":"24","c_Banco":"112","Descripcion":"BMONEX","NombreRazonsocial":"Banco Monex, S.A., Instituci"},
    {"id_Banco":"25","c_Banco":"113","Descripcion":"VE POR MAS","NombreRazonsocial":"Banco Ve Por Mas, S.A. Instituci"},
    {"id_Banco":"26","c_Banco":"116","Descripcion":"ING","NombreRazonsocial":"ING Bank (M"},
    {"id_Banco":"27","c_Banco":"124","Descripcion":"DEUTSCHE","NombreRazonsocial":"Deutsche Bank M"},
    {"id_Banco":"28","c_Banco":"126","Descripcion":"CREDIT SUISSE","NombreRazonsocial":"Banco Credit Suisse (M"},
    {"id_Banco":"29","c_Banco":"127","Descripcion":"AZTECA","NombreRazonsocial":"Banco Azteca, S.A. Instituci"},
    {"id_Banco":"30","c_Banco":"128","Descripcion":"AUTOFIN","NombreRazonsocial":"Banco Autofin M"},
    {"id_Banco":"31","c_Banco":"129","Descripcion":"BARCLAYS","NombreRazonsocial":"Barclays Bank M"},
    {"id_Banco":"32","c_Banco":"130","Descripcion":"COMPARTAMOS","NombreRazonsocial":"Banco Compartamos, S.A., Instituci"},
    {"id_Banco":"33","c_Banco":"131","Descripcion":"BANCO FAMSA","NombreRazonsocial":"Banco Ahorro Famsa, S.A., Instituci"},
    {"id_Banco":"34","c_Banco":"132","Descripcion":"BMULTIVA","NombreRazonsocial":"Banco Multiva, S.A., Instituci"},
    {"id_Banco":"35","c_Banco":"133","Descripcion":"ACTINVER","NombreRazonsocial":"Banco Actinver, S.A. Instituci"},
    {"id_Banco":"36","c_Banco":"134","Descripcion":"WAL-MART","NombreRazonsocial":"Banco Wal-Mart de M"},
    {"id_Banco":"37","c_Banco":"135","Descripcion":"NAFIN","NombreRazonsocial":"Nacional Financiera, Sociedad Nacional de Cr"},
    {"id_Banco":"38","c_Banco":"136","Descripcion":"INTERBANCO","NombreRazonsocial":"Inter Banco, S.A. Instituci"},
    {"id_Banco":"39","c_Banco":"137","Descripcion":"BANCOPPEL","NombreRazonsocial":"BanCoppel, S.A., Instituci"},
    {"id_Banco":"40","c_Banco":"138","Descripcion":"ABC CAPITAL","NombreRazonsocial":"ABC Capital, S.A., Instituci"},
    {"id_Banco":"41","c_Banco":"139","Descripcion":"UBS BANK","NombreRazonsocial":"UBS Bank M"},
    {"id_Banco":"42","c_Banco":"140","Descripcion":"CONSUBANCO","NombreRazonsocial":"Consubanco, S.A. Instituci"},
    {"id_Banco":"43","c_Banco":"141","Descripcion":"VOLKSWAGEN","NombreRazonsocial":"Volkswagen Bank, S.A., Instituci"},
    {"id_Banco":"44","c_Banco":"143","Descripcion":"CIBANCO","NombreRazonsocial":"CIBanco, S.A."},
    {"id_Banco":"45","c_Banco":"145","Descripcion":"BBASE","NombreRazonsocial":"Banco Base, S.A., Instituci"},
    {"id_Banco":"46","c_Banco":"166","Descripcion":"BANSEFI","NombreRazonsocial":"Banco del Ahorro Nacional y Servicios Financieros, Sociedad Nacional de Cr"},
    {"id_Banco":"47","c_Banco":"168","Descripcion":"HIPOTECARIA FEDERAL","NombreRazonsocial":"Sociedad Hipotecaria Federal, Sociedad Nacional de Cr"},
    {"id_Banco":"48","c_Banco":"600","Descripcion":"MONEXCB","NombreRazonsocial":"Monex Casa de Bolsa, S.A. de C.V. Monex Grupo Financiero"},
    {"id_Banco":"49","c_Banco":"601","Descripcion":"GBM","NombreRazonsocial":"GBM Grupo Burs"},
    {"id_Banco":"50","c_Banco":"602","Descripcion":"MASARI","NombreRazonsocial":"Masari Casa de Bolsa, S.A."},
    {"id_Banco":"51","c_Banco":"605","Descripcion":"VALUE","NombreRazonsocial":"Value, S.A. de C.V. Casa de Bolsa"},
    {"id_Banco":"52","c_Banco":"606","Descripcion":"ESTRUCTURADORES","NombreRazonsocial":"Estructuradores del Mercado de Valores Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"53","c_Banco":"607","Descripcion":"TIBER","NombreRazonsocial":"Casa de Cambio Tiber, S.A. de C.V."},
    {"id_Banco":"54","c_Banco":"608","Descripcion":"VECTOR","NombreRazonsocial":"Vector Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"55","c_Banco":"610","Descripcion":"B&B","NombreRazonsocial":"B y B, Casa de Cambio, S.A. de C.V."},
    {"id_Banco":"56","c_Banco":"614","Descripcion":"ACCIVAL","NombreRazonsocial":"Acciones y Valores Banamex, S.A. de C.V., Casa de Bolsa"},
    {"id_Banco":"57","c_Banco":"615","Descripcion":"MERRILL LYNCH","NombreRazonsocial":"Merrill Lynch M"},
    {"id_Banco":"58","c_Banco":"616","Descripcion":"FINAMEX","NombreRazonsocial":"Casa de Bolsa Finamex, S.A. de C.V."},
    {"id_Banco":"59","c_Banco":"617","Descripcion":"VALMEX","NombreRazonsocial":"Valores Mexicanos Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"60","c_Banco":"618","Descripcion":"UNICA","NombreRazonsocial":"Unica Casa de Cambio, S.A. de C.V."},
    {"id_Banco":"61","c_Banco":"619","Descripcion":"MAPFRE","NombreRazonsocial":"MAPFRE Tepeyac, S.A."},
    {"id_Banco":"62","c_Banco":"620","Descripcion":"PROFUTURO","NombreRazonsocial":"Profuturo G.N.P., S.A. de C.V., Afore"},
    {"id_Banco":"63","c_Banco":"621","Descripcion":"CB ACTINVER","NombreRazonsocial":"Actinver Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"64","c_Banco":"622","Descripcion":"OACTIN","NombreRazonsocial":"OPERADORA ACTINVER, S.A. DE C.V."},
    {"id_Banco":"65","c_Banco":"623","Descripcion":"SKANDIA","NombreRazonsocial":"Skandia Vida, S.A. de C.V."},
    {"id_Banco":"66","c_Banco":"626","Descripcion":"CBDEUTSCHE","NombreRazonsocial":"Deutsche Securities, S.A. de C.V. CASA DE BOLSA"},
    {"id_Banco":"67","c_Banco":"627","Descripcion":"ZURICH","NombreRazonsocial":"Zurich Compa"},
    {"id_Banco":"68","c_Banco":"628","Descripcion":"ZURICHVI","NombreRazonsocial":"Zurich Vida, Compa"},
    {"id_Banco":"69","c_Banco":"629","Descripcion":"SU CASITA","NombreRazonsocial":"Hipotecaria Su Casita, S.A. de C.V. SOFOM ENR"},
    {"id_Banco":"70","c_Banco":"630","Descripcion":"CB INTERCAM","NombreRazonsocial":"Intercam Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"71","c_Banco":"631","Descripcion":"CI BOLSA","NombreRazonsocial":"CI Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"72","c_Banco":"632","Descripcion":"BULLTICK CB","NombreRazonsocial":"Bulltick Casa de Bolsa, S.A., de C.V."},
    {"id_Banco":"73","c_Banco":"633","Descripcion":"STERLING","NombreRazonsocial":"Sterling Casa de Cambio, S.A. de C.V."},
    {"id_Banco":"74","c_Banco":"634","Descripcion":"FINCOMUN","NombreRazonsocial":"Fincom"},
    {"id_Banco":"75","c_Banco":"636","Descripcion":"HDI SEGUROS","NombreRazonsocial":"HDI Seguros, S.A. de C.V."},
    {"id_Banco":"76","c_Banco":"637","Descripcion":"ORDER","NombreRazonsocial":"Order Express Casa de Cambio, S.A. de C.V"},
    {"id_Banco":"77","c_Banco":"638","Descripcion":"AKALA","NombreRazonsocial":"Akala, S.A. de C.V., Sociedad Financiera Popular"},
    {"id_Banco":"78","c_Banco":"640","Descripcion":"CB JPMORGAN","NombreRazonsocial":"J.P. Morgan Casa de Bolsa, S.A. de C.V. J.P. Morgan Grupo Financiero"},
    {"id_Banco":"79","c_Banco":"642","Descripcion":"REFORMA","NombreRazonsocial":"Operadora de Recursos Reforma, S.A. de C.V., S.F.P."},
    {"id_Banco":"80","c_Banco":"646","Descripcion":"STP","NombreRazonsocial":"Sistema de Transferencias y Pagos STP, S.A. de C.V.SOFOM ENR"},
    {"id_Banco":"81","c_Banco":"647","Descripcion":"TELECOMM","NombreRazonsocial":"Telecomunicaciones de M"},
    {"id_Banco":"82","c_Banco":"648","Descripcion":"EVERCORE","NombreRazonsocial":"Evercore Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"83","c_Banco":"649","Descripcion":"SKANDIA","NombreRazonsocial":"Skandia Operadora de Fondos, S.A. de C.V."},
    {"id_Banco":"84","c_Banco":"651","Descripcion":"SEGMTY","NombreRazonsocial":"Seguros Monterrey New York Life, S.A de C.V"},
    {"id_Banco":"85","c_Banco":"652","Descripcion":"ASEA","NombreRazonsocial":"Soluci"},
    {"id_Banco":"86","c_Banco":"653","Descripcion":"KUSPIT","NombreRazonsocial":"Kuspit Casa de Bolsa, S.A. de C.V."},
    {"id_Banco":"87","c_Banco":"655","Descripcion":"SOFIEXPRESS","NombreRazonsocial":"J.P. SOFIEXPRESS, S.A. de C.V., S.F.P."},
    {"id_Banco":"88","c_Banco":"656","Descripcion":"UNAGRA","NombreRazonsocial":"UNAGRA, S.A. de C.V., S.F.P."},
    {"id_Banco":"89","c_Banco":"659","Descripcion":"OPCIONES EMPRESARIALES DEL NOROESTE","NombreRazonsocial":"OPCIONES EMPRESARIALES DEL NORESTE, S.A. DE C.V., S.F.P."},
    {"id_Banco":"90","c_Banco":"901","Descripcion":"CLS","NombreRazonsocial":"Cls Bank International"},
    {"id_Banco":"91","c_Banco":"902","Descripcion":"INDEVAL","NombreRazonsocial":"SD. Indeval, S.A. de C.V."},
    {"id_Banco":"92","c_Banco":"670","Descripcion":"LIBERTAD","NombreRazonsocial":"Libertad Servicios Financieros, S.A. De C.V."}]
